/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.event.ActionListener;
import java.util.List;
import javax.swing.DefaultListModel;

/**
 *
 * @author W10-Portable
 */
public class MainJFrame extends javax.swing.JFrame {
    private DefaultListModel<String> modelChat;
    private DefaultListModel<String> modelUsers;
    
    /**
     * Creates new form MainJFrame
     */
    public MainJFrame() {
        initComponents();
        this.modelChat = new DefaultListModel<>();
        this.modelUsers = new DefaultListModel<>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        registerUserLayeredPane = new javax.swing.JLayeredPane();
        registerNameTextField = new javax.swing.JTextField();
        accessChatButton = new javax.swing.JButton();
        chatMessengerLayeredPane = new javax.swing.JLayeredPane();
        historialMessagesScrollPane = new javax.swing.JScrollPane();
        historialMessagesList = new javax.swing.JList<>();
        userMessageTextField = new javax.swing.JTextField();
        usersScrollPane = new javax.swing.JScrollPane();
        usersList = new javax.swing.JList<>();
        sendMessageButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        registerNameTextField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        accessChatButton.setText("Acceder");

        registerUserLayeredPane.setLayer(registerNameTextField, javax.swing.JLayeredPane.DEFAULT_LAYER);
        registerUserLayeredPane.setLayer(accessChatButton, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout registerUserLayeredPaneLayout = new javax.swing.GroupLayout(registerUserLayeredPane);
        registerUserLayeredPane.setLayout(registerUserLayeredPaneLayout);
        registerUserLayeredPaneLayout.setHorizontalGroup(
            registerUserLayeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registerUserLayeredPaneLayout.createSequentialGroup()
                .addGap(216, 216, 216)
                .addGroup(registerUserLayeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(accessChatButton, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                    .addComponent(registerNameTextField))
                .addContainerGap(204, Short.MAX_VALUE))
        );
        registerUserLayeredPaneLayout.setVerticalGroup(
            registerUserLayeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registerUserLayeredPaneLayout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(registerNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(accessChatButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(124, Short.MAX_VALUE))
        );

        historialMessagesScrollPane.setViewportView(historialMessagesList);

        userMessageTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        usersScrollPane.setViewportView(usersList);

        sendMessageButton.setText("Enviar");

        chatMessengerLayeredPane.setLayer(historialMessagesScrollPane, javax.swing.JLayeredPane.DEFAULT_LAYER);
        chatMessengerLayeredPane.setLayer(userMessageTextField, javax.swing.JLayeredPane.DEFAULT_LAYER);
        chatMessengerLayeredPane.setLayer(usersScrollPane, javax.swing.JLayeredPane.DEFAULT_LAYER);
        chatMessengerLayeredPane.setLayer(sendMessageButton, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout chatMessengerLayeredPaneLayout = new javax.swing.GroupLayout(chatMessengerLayeredPane);
        chatMessengerLayeredPane.setLayout(chatMessengerLayeredPaneLayout);
        chatMessengerLayeredPaneLayout.setHorizontalGroup(
            chatMessengerLayeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(chatMessengerLayeredPaneLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(chatMessengerLayeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(historialMessagesScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 384, Short.MAX_VALUE)
                    .addComponent(userMessageTextField))
                .addGap(18, 18, 18)
                .addGroup(chatMessengerLayeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(usersScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                    .addComponent(sendMessageButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        chatMessengerLayeredPaneLayout.setVerticalGroup(
            chatMessengerLayeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(chatMessengerLayeredPaneLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(chatMessengerLayeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(usersScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
                    .addComponent(historialMessagesScrollPane))
                .addGap(18, 18, 18)
                .addGroup(chatMessengerLayeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(userMessageTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(sendMessageButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(registerUserLayeredPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(chatMessengerLayeredPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {chatMessengerLayeredPane, registerUserLayeredPane});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(registerUserLayeredPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chatMessengerLayeredPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {chatMessengerLayeredPane, registerUserLayeredPane});

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public void setAccessChatButtonActionListener(ActionListener al){
        this.accessChatButton.addActionListener(al);
    }
    
    public void setSendMessageButtonActionListener(ActionListener al){
        this.sendMessageButton.addActionListener(al);
    }
    
    public String getTextUserMessageTextField(){
        if(!this.userMessageTextField.getText().isEmpty()){
            return this.userMessageTextField.getText();
        }
        return null;
    }
    
    public String getTextRegisterNameTextField(){
        if(!this.registerNameTextField.getText().isEmpty()){
            return this.registerNameTextField.getText();
        }
        return null;
    }
    
    public void addItemToHistorialMessagesList(String message){
        this.modelChat.addElement(message);
        this.historialMessagesList.setModel(modelChat);
    }
    
    public void addItemToUsersList(String user){
        this.modelUsers.addElement(user);
        this.usersList.setModel(modelUsers);
    }
    
    public void enableSendMessageButton(boolean show){
        this.sendMessageButton.setEnabled(show);
    }
    
    public void enableAccessChatButton(boolean show){
        this.accessChatButton.setEnabled(show);
    }
    
    public void showRegisterLayeredPane(){
        this.registerUserLayeredPane.setVisible(true);
        this.chatMessengerLayeredPane.setVisible(false);
        pack();
    }
    
    public void showChatMessengerLayeredPane(){
        this.chatMessengerLayeredPane.setVisible(true);
        this.registerUserLayeredPane.setVisible(false);
        pack();
    }
    
    public void clearListUsers(){
        this.modelUsers.clear();
        this.usersList.setModel(modelUsers);
    }
    
    public List<String> getListUsers(){
        return (List<String>) this.usersList;
    }
    
    public void clearTextRegisterNameTextField(){
        this.registerNameTextField.setText("");
    }
    
    public void clearTextUserMessageTextField(){
        this.userMessageTextField.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton accessChatButton;
    private javax.swing.JLayeredPane chatMessengerLayeredPane;
    private javax.swing.JList<String> historialMessagesList;
    private javax.swing.JScrollPane historialMessagesScrollPane;
    private javax.swing.JTextField registerNameTextField;
    private javax.swing.JLayeredPane registerUserLayeredPane;
    private javax.swing.JButton sendMessageButton;
    private javax.swing.JTextField userMessageTextField;
    private javax.swing.JList<String> usersList;
    private javax.swing.JScrollPane usersScrollPane;
    // End of variables declaration//GEN-END:variables
}
